### 1. Write a function so that the columns of the output matrix are powers of the input vector.

In [1]:
import numpy as np
a = np.array([1,2,4,6])
Y =4
mat = np.vander(a,Y)
print(mat)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 64  16   4   1]
 [216  36   6   1]]


### 2. Write a function to find moving average in an array over a window: 
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [2]:
def movingavg(a,n):
    sum = np.cumsum(a,dtype =int)
    sum[n:] = sum[n:] - sum[:-n]
    return sum[n - 1:] / n
    
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
n= 3
movingavg(arr,n)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])